<?php

namespace Tk\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TGroupRepository extends EntityRepository
{
}
