tk_api_user:
    pattern: /api/user
    defaults: { _controller: TkAPIBundle:Api:user }

tk_api_profile:
    pattern: /api/profile
    defaults: { _controller: TkAPIBundle:Api:getProfile }

tk_api_groups:
    pattern: /api/groups
    defaults: { _controller: TkAPIBundle:Group:getGroups }
tk_api_groups_post:
    pattern: /api/post/group
    defaults: { _controller: TkAPIBundle:Group:postGroup }
tk_api_group_facebook:
    pattern: /api/group/facebook
    defaults: { _controller: TkAPIBundle:Group:addFriends }
tk_api_group_manual:
    pattern: /api/group/manual
    defaults: { _controller: TkAPIBundle:Group:addManual }
tk_api_group_remove:
    pattern: /api/group/remove
    defaults: { _controller: TkAPIBundle:Group:removeFriends }
tk_api_close_group:
    pattern: /api/group/close
    defaults: { _controller: TkAPIBundle:Group:closeGroup }

tk_api_friends:
    pattern: /api/friends
    defaults: { _controller: TkAPIBundle:Api:getFriends }

tk_api_expenses:
    pattern: /api/expenses
    defaults: { _controller: TkAPIBundle:Api:getExpenses }
tk_api_expense:
    pattern: /api/post/expense
    defaults: { _controller: TkAPIBundle:Api:postExpense }
tk_api_expense_delete:
    pattern: /api/delete/expense
    defaults: { _controller: TkAPIBundle:Api:deleteExpense }

tk_api_dashboard:
    pattern: /api/dashboard
    defaults: { _controller: TkAPIBundle:Api:getDashboardInfo }

tk_api_facebook_token:
    pattern: /app/get/token
    defaults: { _controller: TkAPIBundle:OAuth:facebookToken }
tk_api_facebook_merge:
    pattern: /api/facebook/merge
    defaults: { _controller: TkAPIBundle:OAuth:mergeFacebookAccount }

tk_api_register:
    pattern: /app/register
    defaults: { _controller: TkAPIBundle:OAuth:appRegister }

tk_api_feedback:
    pattern: /api/feedback
    defaults: { _controller: TkAPIBundle:Api:postFeedback }