tk_api_facebook_token:
    pattern: /app/get/token
    defaults: { _controller: TkAPIBundle:OAuth:facebookToken }

tk_api_register:
    pattern: /app/register
    defaults: { _controller: TkAPIBundle:OAuth:appRegister }

tk_api_articles:
    pattern: /api/articles
    defaults: { _controller: TkAPIBundle:Api:articles }

tk_api_user:
    pattern: /api/user
    defaults: { _controller: TkAPIBundle:Api:user }

tk_api_profile:
    pattern: /api/profile
    defaults: { _controller: TkAPIBundle:Api:getProfile }

tk_api_groups:
    pattern: /api/groups
    defaults: { _controller: TkAPIBundle:Api:getGroups }

tk_api_groups_new:
    pattern: /api/add/group
    defaults: { _controller: TkAPIBundle:Api:addGroup }

tk_api_groups_post:
    pattern: /api/post/group
    defaults: { _controller: TkAPIBundle:Api:postGroup }

tk_api_expenses:
    pattern: /api/expenses
    defaults: { _controller: TkAPIBundle:Api:getExpenses }

tk_api_dashboard:
    pattern: /api/dashboard
    defaults: { _controller: TkAPIBundle:Api:getDashboardInfo }