parameters:
#    tk_admin.example.class: Tk\AdminBundle\Example

services:
#    tk_admin.example:
#        class: %tk_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
