parameters:
#    smoney_action.example.class: Smoney\ActionBundle\Example

services:
#    smoney_action.example:
#        class: %smoney_action.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
