tk_user_homepage:
    pattern:  /
    defaults: { _controller: TkUserBundle:Profile:index }

tk_user_profile_edit:
    pattern:  /profile/edit/{id}
    defaults: { _controller: TkUserBundle:Profile:edit }

tk_user_profilepicture_edit:
    pattern:  /picture/upload
    defaults: { _controller: TkUserBundle:Profile:editProfilePicture }

tk_user_modal:
    pattern:  /group/modal/profile/{id}
    defaults: { _controller: TkUserBundle:Profile:modalProfile }

tk_user_feedback:
    pattern:  /feedback
    defaults: { _controller: TkUserBundle:Profile:feedback }

tk_user_connect_facebook:
    pattern: /connect/facebook
    defaults: { _controller: TkUserBundle:Profile:connectfacebook }

# Facebook button

tk_user_facebook_button:
    pattern: /facebook/button
    defaults: { _controller: TkUserBundle:Facebook:loginButton }
tk_user_facebook_login_url:
    pattern: /facebook/url
    defaults: { _controller: TkUserBundle:Facebook:loginUrl }