tk_user_homepage:
    pattern:  /
    defaults: { _controller: TkUserBundle:Profile:index }

tk_user_profile_edit:
    pattern:  /profile/edit/{id}
    defaults: { _controller: TkUserBundle:Profile:edit }

tk_user_username_edit:
    pattern:  /username/edit/{id}
    defaults: { _controller: TkUserBundle:Profile:editUsername }

tk_user_profilepicture_edit:
    pattern:  /picture/upload
    defaults: { _controller: TkUserBundle:Profile:editProfilePicture }
