tk_group_homepage:
    pattern:  /settings
    defaults: { _controller: TkGroupBundle:Default:index }

tk_group_switch_member:
    pattern:  /switch/{id}
    defaults: { _controller: TkGroupBundle:Default:switch }

tk_group_goto_member:
    pattern:  /goto/{id}
    defaults: { _controller: TkGroupBundle:Default:goTo }
tk_group_goto_expenses:
    pattern:  /goto/expenses/{id}
    defaults: { _controller: TkGroupBundle:Default:goToExpenses }
tk_group_goto_lists:
    pattern:  /goto/lists/{id}
    defaults: { _controller: TkGroupBundle:Default:goToLists }

tk_group_new:
    pattern:  /new
    defaults: { _controller: TkGroupBundle:Default:new }

tk_group_edit:
    pattern:  /edit
    defaults: { _controller: TkGroupBundle:Default:edit }

tk_group_add_members:
    pattern:  /add
    defaults: { _controller: TkGroupBundle:Default:addMembers }
tk_group_add_member:
    pattern:  /add/member
    defaults: { _controller: TkGroupBundle:Default:addMember }
tk_group_add_friend:
    pattern:  /add/friend/{id}
    defaults: { _controller: TkGroupBundle:Default:addFriend }
tk_group_add_remove:
    pattern:  /add/remove/member/{id}
    defaults: { _controller: TkGroupBundle:Default:removeAddedMember }
tk_group_add_validate:
    pattern: /add/validate
    defaults: { _controller: TkGroupBundle:Default:validateMembers }

tk_group_remove_member:
    pattern:  /remove/member/{id}
    defaults: { _controller: TkGroupBundle:Default:removeMemberRequest }
tk_group_close:
    pattern:  /close/{id}
    defaults: { _controller: TkGroupBundle:Default:closeGroup }

tk_group_ajax:
    pattern: /ajax/settings
    defaults: { _controller: TkGroupBundle:Default:ajaxContent }