# --- Default routes --- #

tk_group_homepage:
    pattern:  /group
    defaults: { _controller: TkGroupBundle:Default:index }

tk_group_dashboard:
    pattern:  /dashboard
    defaults: { _controller: TkGroupBundle:Default:dashboard }

tk_group_ajax:
    pattern:  /ajax/dashboard
    defaults: { _controller: TkGroupBundle:Default:ajaxContent }

tk_group_switch_member:
    pattern:  /switch/{id}
    defaults: { _controller: TkGroupBundle:Default:switch }

tk_group_goto_member:
    pattern:  /goto/{id}
    defaults: { _controller: TkGroupBundle:Default:goTo }
tk_group_switch_member:
    pattern:  /switch/{id}
    defaults: { _controller: TkGroupBundle:Default:switch }

tk_group_new:
    pattern:  /new
    defaults: { _controller: TkGroupBundle:Default:new }

tk_group_remove_member:
    pattern:  /remove/member/{id}
    defaults: { _controller: TkGroupBundle:Default:removeMemberRequest }
tk_group_close:
    pattern:  /close/{id}
    defaults: { _controller: TkGroupBundle:Default:closeGroup }

tk_group_new_invitation:
    pattern: /invitation/{id}/{email}
    defaults: { _controller: TkGroupBundle:Default:emailForm }

# --- Dashboard routes --- #

tk_dashboard_summary_modal:
    pattern: /summary/modal
    defaults: { _controller: TkGroupBundle:Dashboard:summaryModal }

tk_dashboard_summary_send:
    pattern: /summary/send
    defaults: { _controller: TkGroupBundle:Dashboard:summarySend }

tk_group_edit:
    pattern:  /edit
    defaults: { _controller: TkGroupBundle:Dashboard:edit }

# --- Add members routes --- #

tk_group_add_members:
    pattern:  /add
    defaults: { _controller: TkGroupBundle:AddMembers:addMembers }
tk_group_add_friend:
    pattern:  /add/friend
    defaults: { _controller: TkGroupBundle:AddMembers:addFriend }
tk_group_add_remove:
    pattern:  /add/remove/member/{id}
    defaults: { _controller: TkGroupBundle:AddMembers:removeAddedMember }
tk_group_add_validate:
    pattern:  /add/validate
    defaults: { _controller: TkGroupBundle:AddMembers:validateMembers }
